# Generated by Django 5.0.7 on 2026-07-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("model_version", models.CharField(max_length=50, unique=True)),
                ("accuracy", models.FloatField()),
                ("precision", models.FloatField()),
                ("recall", models.FloatField()),
                ("f1_score", models.FloatField()),
                ("dataset_size", models.PositiveIntegerField()),
                ("evaluated_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "model metrics",
                "ordering": ["-evaluated_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[("real", "Real"), ("ai_generated", "Generada por IA")],
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(help_text="Confianza de la etiqueta predicha, en [0, 1]."),
                ),
                ("ai_probability", models.FloatField(help_text="P(generado por IA), en [0, 1].")),
                (
                    "face_confidence",
                    models.FloatField(help_text="Confianza de detección de rostro (MTCNN)."),
                ),
                ("processing_time_ms", models.FloatField()),
                ("model_version", models.CharField(max_length=50)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="detection_a_created_7eaf67_idx")
                ],
            },
        ),
    ]
